### ISSUE TITLE
Add Optimize

### ISSUE THREAD

**Issue by falko** [camunda/camunda-cloud-helm#112]
Docs: https://docs.camunda.io/docs/self-managed/optimize-deployment/setup/
Docker Hub: https://hub.docker.com/r/camunda/optimize

**Comment by falko** [comment]
@Zelldon ...in order for Optimize to work?

**Comment by falko** [comment]
Okay found IAM instructions too: https://docs.camunda.io/docs/self-managed/iam/getting-started/docker/setup-environment/

**Comment by Zelldon** [comment]
Maybe this https://github.com/plungu/camunda-optimize-helm helps as input

**Comment by Zelldon** [comment]
supersed by https://github.com/camunda/camunda-cloud-helm/issues/126
