### ISSUE TITLE
New java opts defaults

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-cloud-helm#155]
Use the [zeebe benchmark defaults](https://github.com/camunda-cloud/zeebe/blob/main/benchmarks/setup/default/zeebe-values.yaml#L50-L58)

 ```
  # JavaOpts:
  # DEFAULTS
  JavaOpts: >-
    -XX:MaxRAMPercentage=25.0
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/local/zeebe/data
    -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
    -Xlog:gc*:file=/usr/local/zeebe/data/gc.log:time:filecount=7,filesize=8M
```

**Comment by npepinpe** [comment]
I would remove the `MaxRAMPercentage`, as that's actually the JVM default anyway. Everything else we can keep. Not sure if the gc log will really be useful in support, as I can't remember ever using them except a few times to check for performance issues (and even then, nothing came out), so I would omit it.
