### ISSUE TITLE
Zeebe Simple Monitor Helm Chart

### ISSUE THREAD

**Issue by michelefa1988** [camunda/camunda-cloud-helm#229]
I am in need of a [zeebe simple monitor](https://github.com/camunda-community-hub/zeebe-simple-monitor) helm chart but I see you do not have it. It is possible to include it in this suite? (as an extra service)

**Comment by michelefa1988** [comment]
@Zelldon Would it be possible if I do it myself? I think it would be much easier to do it here than create my own and have 2 forks

**Comment by Zelldon** [comment]
Hey @michelefa1988 thanks for raising this but this is out of scope for this project. We want to have here only the official supported services and charts by camunda. For community supported charts, take a look at https://github.com/camunda-community-hub/community/issues/19 There are plans to create a new repo for such.
